@startuml diagrama_caso_uso
!theme plain
skinparam packageStyle rectangle

title Diagrama de Casos de Uso - LogicRoute

left to right direction

actor "Gerente" as gerente
actor "Secretario" as secretario

rectangle "Sistema de Gestión" {
    
    ' Definición de los casos de uso para gestion de usuarios
    usecase "Alta de Usuario" as UC1
    usecase "Baja de Usuario" as UC2
    usecase "Modificación de Usuario" as UC3
    usecase "Consulta de Usuario" as UC4
    UC1 --|> UC4 : <<include>>
    UC2 --|> UC4 : <<include>>
    UC3 --|> UC4 : <<include>>

    ' Definición de los casos de uso para gestion de tipos
    usecase "Alta de Tipo" as UC5
    usecase "Baja de Tipo" as UC6
    usecase "Modificación de Tipo" as UC7
    usecase "Consulta de Tipo" as UC8
    UC5 --|> UC8 : <<include>>
    UC6 --|> UC8 : <<include>>
    UC7 --|> UC8 : <<include>>

    ' Definición de los casos de uso para gestion de alimentos
    usecase "Alta de Alimento" as UC9
    usecase "Baja de Alimento" as UC10
    usecase "Modificación de Alimento" as UC11
    usecase "Consulta de Alimento" as UC12
    UC9 --|> UC12 : <<include>>
    UC10 --|> UC12 : <<include>>
    UC11 --|> UC12 : <<include>>

    ' Definición de los casos de uso para gestion de galpones
    usecase "Alta de Galpón" as UC13
    usecase "Baja de Galpón" as UC14
    usecase "Modificación de Galpón" as UC15
    usecase "Consulta de Galpón" as UC16
    UC13 --|> UC16 : <<include>>
    UC14 --|> UC16 : <<include>>
    UC15 --|> UC16 : <<include>>

}

gerente --> UC1
gerente --> UC2
gerente --> UC3
secretario --> UC5
secretario --> UC6
secretario --> UC7
secretario --> UC9
secretario --> UC10
secretario --> UC11
secretario --> UC13
secretario --> UC14
secretario --> UC15

@enduml